#ifndef JULIA_COURSEWORK_WORKING_TIME_AND_SCREENSIZE_SRV_H
#define JULIA_COURSEWORK_WORKING_TIME_AND_SCREENSIZE_SRV_H

#include <X11/Xlib.h>
#include <utility>

#endif //JULIA_COURSEWORK_WORKING_TIME_AND_SCREENSIZE_SRV_H
